# ---------------------------------------------------------------------------
# Synthetic genotypes, so the simulation pipeline runs without UK Biobank access.
#
# The simulations in the paper draw genotypes from UK Biobank, which cannot be
# redistributed.  This file provides a drop-in substitute that reproduces the
# STRUCTURE the pipeline depends on -- contiguous SNP windows carrying linkage
# disequilibrium, one window per chromosome -- but not the data itself, so
# results obtained with it will differ from the published numbers.
#
# LD is generated by an AR(1) haplotype model: adjacent SNPs are correlated with
# coefficient `rho`, decaying with distance, and two haplotypes are summed to
# give 0/1/2 dosages.  rho = 0.85 gives a mean within-window pairwise r^2 close
# to the value measured in the UK Biobank windows used in the paper.
#
# Usage, replacing the two lines that open the real data in any gen_sim_*.R:
#
#     source("data/synthetic_genotypes.R")
#     syn = synthetic_panel(nInd = 5000, nChr = 20, nSNPperChr = 2000)
#     bm = syn$bm; bim = syn$bim
#
# `bm` is a plain matrix and `bim` a data.frame with the columns the generators
# use (V1 = chromosome, V4 = base-pair position), which is all that
# Simdata.LD() and Simdata.LD.INT() require of them.
# ---------------------------------------------------------------------------

#' @param nInd       individuals in the panel
#' @param nChr       chromosomes (the generators place one region per chromosome,
#'                   so this caps the number of regions)
#' @param nSNPperChr SNPs per chromosome
#' @param rho        AR(1) correlation between adjacent SNPs on a haplotype
#' @param maf.range  range of minor allele frequencies
synthetic_panel = function(nInd = 5000, nChr = 20, nSNPperChr = 2000,
                           rho = 0.85, maf.range = c(0.05, 0.5), seed = 1) {
  set.seed(seed)
  hap = function(n, m) {                      # one AR(1) haplotype block
    z = matrix(0, n, m)
    z[, 1] = rnorm(n)
    for (j in 2:m) z[, j] = rho * z[, j-1] + sqrt(1 - rho^2) * rnorm(n)
    z
  }
  blocks = lapply(seq_len(nChr), function(c) {
    maf = runif(nSNPperChr, maf.range[1], maf.range[2])
    thr = qnorm(maf)                          # threshold a latent normal at the MAF
    a = sweep(hap(nInd, nSNPperChr), 2, thr, "<") * 1L
    b = sweep(hap(nInd, nSNPperChr), 2, thr, "<") * 1L
    a + b                                     # 0/1/2 dosage
  })
  bm = do.call(cbind, blocks)
  storage.mode(bm) = "integer"
  bim = data.frame(
    V1 = rep(seq_len(nChr), each = nSNPperChr),                 # chromosome
    V2 = sprintf("rs%07d", seq_len(nChr * nSNPperChr)),         # id
    V3 = 0,
    V4 = rep(seq_len(nSNPperChr) * 1000L, times = nChr),        # bp, 1 kb spacing
    stringsAsFactors = FALSE)
  colnames(bm) = bim$V2
  list(bm = bm, bim = bim)
}

#' Mean within-window pairwise r^2, for checking the panel against the paper.
#' The UK Biobank windows used in the paper average about 0.045; SNPs drawn at
#' random across the genome average about 0.004.
window_r2 = function(bm, bim, nSNP = 20, nWindow = 50) {
  v = replicate(nWindow, {
    c  = sample(unique(bim$V1), 1)
    ix = which(bim$V1 == c)
    s  = sample(length(ix) - nSNP, 1)
    G  = bm[, ix[s:(s + nSNP - 1)], drop = FALSE]
    G  = G[, apply(G, 2, sd) > 0, drop = FALSE]
    r  = cor(G)^2
    mean(r[upper.tri(r)])
  })
  mean(v)
}
